const API="https://api.alquran.cloud/v1";
const ALADHAN="https://api.aladhan.com/v1";
const state={route:"home",surahs:[],loaded:false,currentSurah:null,bookmarks:JSON.parse(localStorage.getItem("nq_bookmarks")||"[]"),favorites:JSON.parse(localStorage.getItem("nq_favorites")||"[]"),history:JSON.parse(localStorage.getItem("nq_history")||"[]"),dark:localStorage.getItem("nq_dark")==="1",audio:null};

function $(s){return document.querySelector(s)} function esc(s){return String(s??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]))}
function save(){localStorage.setItem("nq_bookmarks",JSON.stringify(state.bookmarks));localStorage.setItem("nq_favorites",JSON.stringify(state.favorites));localStorage.setItem("nq_history",JSON.stringify(state.history));localStorage.setItem("nq_dark",state.dark?"1":"0")}
function toast(t){const x=document.createElement("div");x.className="toast";x.textContent=t;document.body.appendChild(x);setTimeout(()=>x.remove(),2200)}
function dismissSplash(){$("#splash").classList.add("hide");localStorage.setItem("nq_visited","1")}
if(localStorage.getItem("nq_visited"))dismissSplash();
document.body.classList.toggle("dark",state.dark);

function openDrawer(){$("#drawer").classList.add("open")}function closeDrawer(){$("#drawer").classList.remove("open")}
function go(r){closeDrawer();navigate(r)}
function navigate(r){state.route=r;render();window.scrollTo(0,0)}
function setActive(r){document.querySelectorAll(".bottomNav button").forEach(b=>b.classList.toggle("active",b.dataset.route===r))}
async function render(){setActive(state.route);const s=$("#screen");s.innerHTML=`<div class="empty">লোড হচ্ছে...</div>`;try{
if(state.route==="home")s.innerHTML=await home(); else if(state.route==="library")s.innerHTML=await library(); else if(state.route==="reader")s.innerHTML=await reader(); else if(state.route==="search")s.innerHTML=search(); else if(state.route==="favorite")s.innerHTML=favorite(); else if(state.route==="prayer")s.innerHTML=await prayer(); else if(state.route==="settings")s.innerHTML=settings(); else if(state.route==="qibla")s.innerHTML=await qibla(); else if(state.route==="audio")s.innerHTML=audio(); else if(state.route==="tafsir")s.innerHTML=tafsir(); else s.innerHTML=extra(state.route);
}catch(e){s.innerHTML=`<div class="card panel"><h3>লোড করা যায়নি</h3><p>${esc(e.message)}</p><button class="pill" onclick="render()">আবার চেষ্টা করুন</button></div>`}}
async function loadSurahs(){if(state.loaded)return state.surahs;const r=await fetch(API+"/surah");if(!r.ok)throw Error("Quran server থেকে সূরার তালিকা পাওয়া যায়নি");const j=await r.json();state.surahs=j.data;state.loaded=true;return state.surahs}
function surahCard(x){return `<button class="surah" onclick="openSurah(${x.number})"><span class="num">${x.number}</span><span class="sInfo"><strong>${esc(x.englishNameTranslation||x.englishName)}</strong><small>${esc(x.englishName)} • আয়াত ${x.numberOfAyahs} • ${x.revelationType==="Meccan"?"মাক্কী":"মাদানী"}</small></span><span class="arabicName">${esc(x.name)}</span></button>`}
async function home(){const ss=await loadSurahs();return `<section class="hero"><div class="heroTop"><div><div class="location">📍 Al-Qatif</div><h2 id="homeClock">--:--</h2><small>পরবর্তী নামাজের সময় দেখুন নিচে</small></div><div class="mosque">🕌</div></div><div class="prayerStrip"><div class=pTime>ফজর<b>--:--</b></div><div class=pTime>যোহর<b>--:--</b></div><div class=pTime>আসর<b>--:--</b></div><div class=pTime>মাগরিব<b>--:--</b></div><div class=pTime>ইশা<b>--:--</b></div></div></section>
<div class=continue><small>📖 পড়া চালিয়ে যান</small><div class=continueRow><div><h2>আল-ফাতিহা</h2><small>আয়াত ১ - ৭</small></div><button class=pill onclick="openSurah(1)">শুরু করুন ▶</button></div></div>
<div class=quickGrid>${[["📖","কুরআন","library"],["▥","তাফসীর","tafsir"],["🔊","অডিও","audio"],["♧","নামাজ","prayer"],["◉","কিবলা","qibla"],["⌕","সার্চ","search"],["▮","বুকমার্ক","favorite"],["⚙","সেটিংস","settings"]].map(x=>`<button class=quick onclick="navigate('${x[2]}')"><i>${x[0]}</i><span>${x[1]}</span></button>`).join("")}</div>
<h2 class=sectionTitle>সূরাসমূহ</h2>${ss.slice(0,8).map(surahCard).join("")}`}

async function library(){const ss=await loadSurahs();return `<div class=search>⌕<input id=surahQ placeholder="সূরা নাম / নম্বর খুঁজুন" oninput="filterSurahs(this.value)"></div><div class=tabs><button class="tab active">সব</button><button class=tab>মাক্কী</button><button class=tab>মাদানী</button></div><div id=surahList>${ss.map(surahCard).join("")}</div>`}
function filterSurahs(q){const a=state.surahs.filter(x=>(x.englishName+" "+x.englishNameTranslation+" "+x.name+" "+x.number).toLowerCase().includes(q.toLowerCase()));$("#surahList").innerHTML=a.map(surahCard).join("")||`<div class=empty>কিছু পাওয়া যায়নি</div>`}

async function openSurah(n){state.currentSurah=n;state.history=[n,...state.history.filter(x=>x!==n)].slice(0,20);save();navigate("reader")}
async function reader(){const n=state.currentSurah||1;const arab=fetch(`${API}/surah/${n}/quran-uthmani`).then(r=>r.json());const bn=fetch(`${API}/surah/${n}/bn.bengali`).then(r=>r.json());const en=fetch(`${API}/surah/${n}/en.sahih`).then(r=>r.json());const [a,b,e]=await Promise.all([arab,bn,en]);const meta=a.data;const arr=meta.ayahs.map((v,i)=>({ar:v.text,bn:b.data.ayahs[i]?.text||"",en:e.data.ayahs[i]?.text||"",num:v.numberInSurah,global:v.number}));return `<div class=readerHead><h2>${esc(meta.englishNameTranslation||meta.englishName)}</h2><small>${esc(meta.name)} • ${meta.revelationType==="Meccan"?"মাক্কী":"মাদানী"} • ${meta.numberOfAyahs} আয়াত</small></div><div class=tabs><button class="tab active">কুরআন</button><button class=tab>অনুবাদ</button><button class=tab onclick="toast('তাফসীর সংযোগটি backend credentials চাইতে পারে')">তাফসীর</button></div>${arr.map(v=>ayahHtml(v,n)).join("")}`}
function ayahHtml(v,n){const bm=state.bookmarks.includes(`${n}:${v.num}`),fav=state.favorites.includes(`${n}:${v.num}`);return `<article class=ayah id="a-${n}-${v.num}"><div class=ayahNo><span>${n}:${v.num}</span><span>${bm?"🔖":""}</span></div><div class=ar>${esc(v.ar)}</div><div class=bn>${esc(v.bn)}</div><div class=en>${esc(v.en)}</div><div class=actions><button class=smallBtn onclick="toggleSave('bookmark','${n}:${v.num}')">${bm?"🔖 Saved":"🔖 Bookmark"}</button><button class=smallBtn onclick="toggleSave('favorite','${n}:${v.num}')">${fav?"♥ Saved":"♡ Favorite"}</button><button class=smallBtn onclick="playAyah(${v.global})">▶ Audio</button><button class=smallBtn onclick="shareAyah('${n}:${v.num}')">↗</button></div></article>`}

function toggleSave(type,key){const a=type==="bookmark"?state.bookmarks:state.favorites;const i=a.indexOf(key);if(i>=0)a.splice(i,1);else a.push(key);save();render()}
function shareAyah(key){if(navigator.share)navigator.share({title:"কুরআন",text:"কুরআন আয়াত "+key});else toast("Share অপশন এই ডিভাইসে নেই")}
function playAyah(global){const p=$("#player");p.src=`https://cdn.islamic.network/quran/audio/128/ar.alafasy/${global}.mp3`;p.play().then(()=>toast("অডিও চলছে")).catch(()=>toast("অডিও চালু করা যায়নি"))}

function search(){return `<div class=search>⌕<input id=searchInput autofocus placeholder="কুরআনে খুঁজুন..." oninput="doSearch(this.value)"></div><div class=tabs><button class="tab active">কুরআন</button><button class=tab>সূরা</button><button class=tab>আয়াত</button></div><div id=searchResults class=empty>শব্দ লিখে সার্চ করুন</div>`}
let searchTimer;function doSearch(q){clearTimeout(searchTimer);if(!q||q.length<2){$("#searchResults").innerHTML=`<div class=empty>কমপক্ষে ২টি অক্ষর লিখুন</div>`;return}searchTimer=setTimeout(async()=>{try{const r=await fetch(`${API}/search/${encodeURIComponent(q)}/all/bn.bengali`);const j=await r.json();const hits=j.data?.matches||[];$("#searchResults").innerHTML=hits.slice(0,30).map(h=>`<button class=surah onclick="openSurah(${h.surah.number})"><span class=num>${h.numberInSurah}</span><span class=sInfo><strong>${esc(h.surah.englishNameTranslation)}</strong><small>${esc(h.text)}</small></span></button>`).join("")||`<div class=empty>ফলাফল পাওয়া যায়নি</div>`}catch(e){$("#searchResults").innerHTML=`<div class=empty>সার্চ API সাময়িকভাবে পাওয়া যাচ্ছে না</div>`}},350)}

function favorite(){if(!state.favorites.length)return `<div class=card panel><h2>ফেভারিট</h2><div class=empty>এখনও কোনো আয়াত ফেভারিট করা হয়নি।</div></div>`;return `<h2 class=sectionTitle>ফেভারিট আয়াত</h2>${state.favorites.map(k=>`<button class=surah onclick="openSurah(${k.split(":")[0]})"><span class=num>♥</span><span class=sInfo><strong>সূরা ${k.split(":")[0]} • আয়াত ${k.split(":")[1]}</strong><small>Reader খুলুন</small></span></button>`).join("")}`}
async function prayer(){const today=new Date();const city="Qatif";const country="Saudi Arabia";const r=await fetch(`${ALADHAN}/timingsByCity/${today.getDate()}-${today.getMonth()+1}-${today.getFullYear()}?city=${encodeURIComponent(city)}&country=${encodeURIComponent(country)}&method=4`);const j=await r.json();const t=j.data.timings;return `<div class=hero><div class=heroTop><div><div class=location>📍 ${city}, ${country}</div><h2>${esc(t.Asr)}</h2><small>আজকের নামাজের সময়</small></div><div class=mosque>🕌</div></div><div class=prayerStrip>${[["ফজর",t.Fajr],["যোহর",t.Dhuhr],["আসর",t.Asr],["মাগরিব",t.Maghrib],["ইশা",t.Isha]].map(x=>`<div class=pTime>${x[0]}<b>${x[1]}</b></div>`).join("")}</div></div><div class="card panel"><h2>আজকের সময়</h2><p>সূর্যোদয়: ${t.Sunrise}</p><p>সূর্যাস্ত: ${t.Sunset}</p><p>মধ্যরাত: ${t.Midnight||"--"}</p><small>গণনার পদ্ধতি/স্থানীয় মসজিদের সময়ের সাথে পার্থক্য হতে পারে।</small></div>`}
async function qibla(){const r=await fetch(`${ALADHAN}/qibla/24.9226/50.0614`);const j=await r.json();const d=j.data.direction;return `<div class="card panel"><h2>কিবলা দিক</h2><div class=bigIcon>🧭</div><h2 style="text-align:center;color:var(--green)">${Number(d).toFixed(1)}°</h2><p style="text-align:center">কাবা শরীফের দিক — Qatif-এর জন্য</p><p style="text-align:center">ডিভাইসের compass থাকলে আরও নির্ভুল orientation যোগ করা যাবে।</p></div>`}

function settings(){return `<h2 class=sectionTitle>সেটিংস</h2><div class="card panel"><div class=row><span>🌐 ভাষা</span><b>বাংলা</b></div><div class=row><span>🔤 আরবি ফন্ট</span><b>Uthmani</b></div><div class=row><span>🔠 ফন্ট সাইজ</span><button class=smallBtn onclick="fontSize()">A / A+</button></div><div class=row><span>🌙 Dark Mode</span><button class="switch ${state.dark?"on":""}" onclick="toggleDark()"><i></i></button></div><div class=row><span>🔊 Default Reciter</span><b>Alafasy</b></div><div class=row><span>🔔 Notifications</span><b>On</b></div></div><div class="card panel"><h3>ডাটা</h3><button class=smallBtn onclick="clearLocal()">লোকাল ডাটা মুছুন</button></div>`}
function toggleDark(){state.dark=!state.dark;save();document.body.classList.toggle("dark",state.dark);render()}
function fontSize(){document.body.classList.toggle("largeArabic");toast("আরবি ফন্ট সাইজ পরিবর্তনের জন্য CSS class প্রস্তুত করা হয়েছে")}
function clearLocal(){localStorage.removeItem("nq_bookmarks");localStorage.removeItem("nq_favorites");localStorage.removeItem("nq_history");state.bookmarks=[];state.favorites=[];state.history=[];toast("লোকাল ডাটা মুছে দেওয়া হয়েছে");render()}
function audio(){return `<div class="card panel"><h2>অডিও কুরআন</h2><p>আল-আফাসী • Ayah-by-ayah streaming</p><button class=pill onclick="playAyah(1)">▶ ফাতিহা ১:১ চালান</button><hr><p>পূর্ণ সূরা অডিও CDN থেকেও stream করা যায়।</p><button class=smallBtn onclick="window.open('https://cdn.islamic.network/quran/audio-surah/128/ar.alafasy/1.mp3','_blank')">পূর্ণ সূরা ফাতিহা</button></div>`}
function tafsir(){return `<div class="card panel"><h2>তাফসীর</h2><p>এই UI-তে আয়াতভিত্তিক তাফসীরের জন্য backend adapter রাখা হয়েছে। Production-এ Quran Foundation Content API ব্যবহার করুন এবং অনুমোদিত tafsir resource নির্বাচন করুন।</p><button class=pill onclick="openSurah(1)">আয়াত পড়ুন</button></div><div class=card panel><h3>শব্দে-শব্দে</h3><p>আরবি শব্দ, উচ্চারণ ও অর্থ দেখানোর জন্য reader-এর word-level data সংযোগ করা যাবে।</p></div>`}
function extra(r){const data={daily:["প্রতিদিন কুরআন - হাদীস","আজকের জন্য একটি আয়াত, অনুবাদ ও হাদীসের পাঠ এখানে সাজানো যাবে।"],printed:["ছাপা কুরআন","মুশহাফ-style page reader; production-এ verified page images/CDN ব্যবহার করুন।"],dictionary:["তাফহীম অভিধান","কুরআনিক শব্দের অর্থ ও অনুসন্ধান।"],tajweed:["তাজবিদ","তাজবিদের নিয়ম, উদাহরণ ও রঙিন Tajweed guide।"],document:["ডোনেশন করুন","আপনার পছন্দের verified donation gateway এখানে যুক্ত করুন।"],request:["Request Submit","নতুন অনুবাদ/ফিচার/সংশোধনের অনুরোধ পাঠানোর ফর্ম।"]};const x=data[r]||["এই বিভাগ","এই ফিচারটি প্রস্তুত করার জায়গা।"];return `<div class="card panel"><h2>${x[0]}</h2><p>${x[1]}</p><textarea id=req style="width:100%;min-height:120px;padding:10px;border:1px solid #ddd;border-radius:12px" placeholder="আপনার লেখা..."></textarea><br><button class=pill onclick="toast('Request/entry সংরক্ষণের জন্য backend যোগ করুন')">Submit</button></div>`}

function rateApp(){toast("Play Store listing যুক্ত হলে Rate action এখানে যাবে")}function updateApp(){toast("PWA/Store update check চালু করা যাবে")}async function shareApp(){if(navigator.share)await navigator.share({title:"নূর কুরআন",text:"কুরআন অ্যাপ"});else toast("Share supported নয়")}function exitApp(){toast("Browser নিরাপত্তার কারণে app নিজে বন্ধ করতে পারে না")}function aboutApp(){openModal(`<button class=close onclick="closeModal()">×</button><h2>তাফহীমুল কুরআন</h2><p>Premium Quran companion app.</p><p>কুরআন • অনুবাদ • তাফসীর • অডিও • নামাজ • কিবলা • বুকমার্ক</p><p>Quran content: AlQuran.cloud API<br>Prayer/Qibla: AlAdhan API</p>`)}

function closeModal(){$("#modal").classList.remove("open")}function openModal(html){$("#modalBox").innerHTML=html;$("#modal").classList.add("open")}
render();
